"""Fetch Google Fonts woff2 files and emit a self-hosted @font-face stylesheet."""
import os, re, urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Bricolage+Grotesque:opsz,wght@12..96,400..700&"
           "family=Figtree:wght@400;500;600;700&"
           "family=DM+Mono:wght@400;500&display=swap")

# A modern UA makes Google serve woff2 rather than legacy ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

DEST = os.path.join(
    r"C:\Users\Dan\Documents\vibe-coding-project\tasker", "assets", "fonts")

# The pages are English-only; dropping the other subsets keeps the package small.
KEEP_SUBSETS = {"latin", "latin-ext"}


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    os.makedirs(DEST, exist_ok=True)
    css = get(CSS_URL)

    # Google emits: /* latin */ @font-face { ... src: url(...) format('woff2'); }
    blocks = re.findall(r"(/\*\s*([\w-]+)\s*\*/\s*)?(@font-face\s*\{[^}]*\})", css)

    out, seen, total = [], {}, 0
    for _, subset, block in blocks:
        if subset and subset not in KEEP_SUBSETS:
            continue

        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        url = m.group(1)

        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()

        if url not in seen:
            slug = family.replace(" ", "") + "-" + weight.replace(" ", "_")
            name = f"{slug}-{subset}-{len(seen)}.woff2"
            data = get(url, binary=True)
            with open(os.path.join(DEST, name), "wb") as f:
                f.write(data)
            seen[url] = name
            total += len(data)
            print(f"  {name:52s} {len(data)/1024:6.1f} KB")

        out.append(re.sub(r"url\(https://[^)]+\.woff2\)",
                          f"url(./{seen[url]})", block))

    header = ("/* Self-hosted webfonts. Bundled with the extension so no request\n"
              "   ever leaves the user's machine to render the UI. Generated by\n"
              "   scripts/fetch_fonts.py - see PUBLISHING_CHECKLIST.md. */\n\n")
    with open(os.path.join(DEST, "fonts.css"), "w", encoding="utf-8") as f:
        f.write(header + "\n\n".join(out) + "\n")

    print(f"\n{len(seen)} files, {total/1024:.0f} KB total -> assets/fonts/")


if __name__ == "__main__":
    main()
